// Generated by scripts/generate-strategy-pack-catalog.mjs. Do not edit.
// Strategy pack digests: {"congressional-signals@1.0.0":"c5031a9d345956d491b35e5459043195437497bc90ce18f8fe8600a596fa8d29","congressional-signals@1.1.0":"54b09e91047f9e34681994eefc5f1284c45b658f55873df49ba3fab3ad211630","ipo-filings@1.0.0":"509e1a06a7bf2d8de6cd216ff894f9353870cc8062fff0945cde4ba7ad2a0fce"}
import type { StrategyPackDefinition } from "./strategy-pack-schema";

export const STRATEGY_PACK_CATALOG_GENERATED: readonly StrategyPackDefinition[] = [
  {
    "capabilities": {
      "hardDenied": [
        "broker.mutation",
        "coinbase_create_order",
        "financial.mutation",
        "filesystem",
        "interactive.approval",
        "masterkey_mcp",
        "private.history",
        "shell",
        "web.search"
      ],
      "required": [
        "evaluate_congressional_signals",
        "skill.congressional-signal-triage"
      ]
    },
    "compatibility": {
      "coreSchemaVersion": 1,
      "strategyPackSchemaVersion": 1,
      "workspaceSchemaVersion": 1
    },
    "configuration": [
      {
        "description": "Timezone used for local House disclosure checks.",
        "key": "timezone",
        "label": "Timezone",
        "mutableAfterInstall": true,
        "pauseManagedMonitorsOnChange": true,
        "required": true,
        "rolloverGenerationOnChange": true,
        "default": "UTC",
        "kind": "iana_timezone"
      },
      {
        "description": "Unique local times when the House disclosure monitor may run.",
        "key": "dailyTimes",
        "label": "Daily check times",
        "mutableAfterInstall": true,
        "pauseManagedMonitorsOnChange": true,
        "required": true,
        "rolloverGenerationOnChange": true,
        "default": [
          "09:00",
          "16:00"
        ],
        "kind": "daily_local_times",
        "maximumItems": 8,
        "minimumItems": 1
      },
      {
        "description": "Lowest deterministic filing band that may produce an alert.",
        "key": "minimumAlertBand",
        "label": "Minimum alert band",
        "mutableAfterInstall": true,
        "pauseManagedMonitorsOnChange": true,
        "required": true,
        "rolloverGenerationOnChange": true,
        "allowedValues": [
          "priority",
          "review"
        ],
        "default": "priority",
        "kind": "bounded_enum"
      },
      {
        "description": "Canonical Bioguide IDs to monitor; empty means all reviewed members.",
        "key": "selectedMemberBioguideIds",
        "label": "Selected House members",
        "mutableAfterInstall": true,
        "pauseManagedMonitorsOnChange": true,
        "required": true,
        "rolloverGenerationOnChange": true,
        "allowedValues": [
          "H001082"
        ],
        "default": [],
        "kind": "canonical_id_list",
        "maximumItems": 1,
        "minimumItems": 0
      }
    ],
    "description": "Triage official House Periodic Transaction Reports with deterministic, neutral research alerts.",
    "displayName": "Congressional Signals",
    "evaluationsPath": "evals.json",
    "id": "congressional-signals",
    "maturity": "reference",
    "monitors": [
      {
        "activationDefault": "paused",
        "alertPresentationId": "alert.public-event/v1",
        "dailyTimesConfigurationKey": "dailyTimes",
        "displayName": "Evaluate House PTR filings",
        "findingSchemaId": "congressional-filing-signal/v1",
        "instructionPath": "monitors/evaluate-house-ptrs.md",
        "overridableFields": [
          "schedule"
        ],
        "requiredCapabilityIds": [
          "evaluate_congressional_signals"
        ],
        "resourceId": "evaluate-house-ptrs",
        "sourceIds": [
          "house-financial-disclosures-2026"
        ],
        "suggestedBudget": {
          "maximumInputTokensPerRun": 12000,
          "maximumOutputTokensPerRun": 2000,
          "maximumRunsPerDay": 8
        },
        "timezoneConfigurationKey": "timezone",
        "instruction": "# Evaluate official House PTRs\n\nCall `evaluate_congressional_signals` once for this occurrence. Do not fetch arbitrary URLs, rescore returned facts, or write a separate finding. A first acquisition establishes history without alerts. Later eligible filings may create one neutral filing-level alert through the managed outbox.\n"
      }
    ],
    "schemaVersion": 1,
    "skills": [
      {
        "description": "Evaluate authorized official House PTR projections using the pinned ordinal policy.",
        "id": "congressional-signal-triage",
        "instructionPath": "playbook.md",
        "version": "1.0.0",
        "instruction": "# House PTR triage\n\nFor each scheduled occurrence, call `evaluate_congressional_signals` exactly once. The capability owns source coordination, normalization, baseline behavior, deterministic banding, persistence, and at-most-once finding creation.\n\nTreat `record_only`, `review`, and `priority` as ordinal research bands, never numeric scores. Unknown mappings remain unknown. Report source or capability failures plainly and do not substitute another source.\n"
      }
    ],
    "sources": [
      {
        "accessClassification": "public",
        "allowedOrigins": [
          "https://disclosures-clerk.house.gov"
        ],
        "canonicalUrl": "https://disclosures-clerk.house.gov/public_disc/financial-pdfs/2026FD.zip",
        "contractDigest": "ef0772fd62d5781c9dac989eb12f699856d909d10ad3b81efe6b5a68c29046bc",
        "contractVersion": "1.0.0",
        "sourceId": "house-financial-disclosures-2026"
      }
    ],
    "version": "1.0.0",
    "workspaceInstructionPath": "workspace.md",
    "contentDigest": "c5031a9d345956d491b35e5459043195437497bc90ce18f8fe8600a596fa8d29",
    "evaluations": {
      "cases": [
        {
          "fixtureId": "fixture.congressional-signals.baseline",
          "id": "congressional-signals-baseline",
          "kind": "no_match"
        },
        {
          "fixtureId": "fixture.congressional-signals.forbidden-capability",
          "id": "congressional-signals-forbidden-capability",
          "kind": "forbidden_capability"
        },
        {
          "fixtureId": "fixture.congressional-signals.non-qualifying",
          "id": "congressional-signals-non-qualifying",
          "kind": "malformed_input"
        },
        {
          "fixtureId": "fixture.congressional-signals.priority",
          "id": "congressional-signals-priority",
          "kind": "positive"
        },
        {
          "fixtureId": "fixture.congressional-signals.replay",
          "id": "congressional-signals-replay",
          "kind": "replay"
        }
      ],
      "schemaVersion": 1,
      "suiteId": "eval.congressional-signals/v1"
    },
    "workspaceInstruction": "# Congressional Signals\n\nThis workspace monitors official House Periodic Transaction Reports (PTRs) only. It is a research-triage workspace, not a trading system and not complete congressional coverage.\n\nUse only the authorized House projection and the `evaluate_congressional_signals` capability. Preserve disclosed ranges and ambiguity. Never infer intent, wrongdoing, exact value, holdings, future returns, or an instruction to trade.\n"
  },
  {
    "capabilities": {
      "hardDenied": [
        "broker.mutation",
        "coinbase_create_order",
        "financial.mutation",
        "filesystem",
        "interactive.approval",
        "masterkey_mcp",
        "private.history",
        "shell",
        "web.search"
      ],
      "required": [
        "evaluate_congressional_signals",
        "skill.congressional-signal-triage"
      ]
    },
    "compatibility": {
      "coreSchemaVersion": 1,
      "strategyPackSchemaVersion": 1,
      "workspaceSchemaVersion": 1
    },
    "configuration": [
      {
        "description": "Timezone used for local House disclosure checks.",
        "key": "timezone",
        "label": "Timezone",
        "mutableAfterInstall": true,
        "pauseManagedMonitorsOnChange": true,
        "required": true,
        "rolloverGenerationOnChange": true,
        "default": "UTC",
        "kind": "iana_timezone"
      },
      {
        "description": "Unique local times when the House disclosure monitor may run.",
        "key": "dailyTimes",
        "label": "Daily check times",
        "mutableAfterInstall": true,
        "pauseManagedMonitorsOnChange": true,
        "required": true,
        "rolloverGenerationOnChange": true,
        "default": [
          "09:00",
          "16:00"
        ],
        "kind": "daily_local_times",
        "maximumItems": 8,
        "minimumItems": 1
      },
      {
        "description": "Lowest deterministic filing band that may produce an alert.",
        "key": "minimumAlertBand",
        "label": "Minimum alert band",
        "mutableAfterInstall": true,
        "pauseManagedMonitorsOnChange": true,
        "required": true,
        "rolloverGenerationOnChange": true,
        "allowedValues": [
          "priority",
          "review"
        ],
        "default": "priority",
        "kind": "bounded_enum"
      },
      {
        "description": "Canonical Bioguide IDs to monitor; empty means all reviewed members.",
        "key": "selectedMemberBioguideIds",
        "label": "Selected House members",
        "mutableAfterInstall": true,
        "pauseManagedMonitorsOnChange": true,
        "required": true,
        "rolloverGenerationOnChange": true,
        "allowedValues": [
          "G000568",
          "H001082"
        ],
        "default": [],
        "kind": "canonical_id_list",
        "maximumItems": 2,
        "minimumItems": 0
      }
    ],
    "description": "Triage official House Periodic Transaction Reports with deterministic, neutral research alerts.",
    "displayName": "Congressional Signals",
    "evidenceContracts": [
      {
        "digest": "aef9afda8bd62b85d12cb675fcddbb8a1e395f0ded2557b3a93d0cb5a5feb98f",
        "id": "congressional-committee-assignments",
        "version": "1.0.0"
      },
      {
        "digest": "4999c6dcc2abd5392104d0be635352fb5a5cc968d1297c58006eb345218c238c",
        "id": "congressional-committee-jurisdictions",
        "version": "1.0.0"
      },
      {
        "digest": "022b90a39b420c8fe2beff426e61a25340bb742786e2a0d875c9d9354b8dd0e1",
        "id": "congressional-house-members",
        "version": "1.1.0"
      },
      {
        "digest": "aa7151cf20154fd462a0999729467bf940864559101ad23694056fddafc1b687",
        "id": "congressional-security-classifications",
        "version": "1.1.0"
      },
      {
        "digest": "21eea262856c2f1fb5b3de4575fdace8cc02491696a0dc4142c879886a46cf92",
        "id": "congressional-signals-policy",
        "version": "1.1.0"
      }
    ],
    "evaluationsPath": "evals.json",
    "id": "congressional-signals",
    "maturity": "reference",
    "monitors": [
      {
        "activationDefault": "paused",
        "alertPresentationId": "alert.public-event/v1",
        "dailyTimesConfigurationKey": "dailyTimes",
        "displayName": "Evaluate House PTR filings",
        "findingSchemaId": "congressional-filing-signal/v1",
        "instructionPath": "monitors/evaluate-house-ptrs.md",
        "overridableFields": [
          "schedule"
        ],
        "requiredCapabilityIds": [
          "evaluate_congressional_signals"
        ],
        "resourceId": "evaluate-house-ptrs",
        "sourceIds": [
          "house-financial-disclosures-2026"
        ],
        "suggestedBudget": {
          "maximumInputTokensPerRun": 12000,
          "maximumOutputTokensPerRun": 2000,
          "maximumRunsPerDay": 8
        },
        "timezoneConfigurationKey": "timezone",
        "instruction": "# Evaluate official House PTRs\n\nCall `evaluate_congressional_signals` once for this occurrence. Do not fetch arbitrary URLs, rescore returned facts, or write a separate finding. A first acquisition establishes history without alerts. Later eligible filings may create one neutral filing-level alert through the managed outbox.\n"
      }
    ],
    "schemaVersion": 1,
    "skills": [
      {
        "description": "Evaluate authorized official House PTR projections using pinned ordinal and committee-evidence policy.",
        "id": "congressional-signal-triage",
        "instructionPath": "playbook.md",
        "version": "1.1.0",
        "instruction": "# House PTR triage\n\nFor each scheduled occurrence, call `evaluate_congressional_signals` exactly once. The capability owns source coordination, normalization, baseline behavior, deterministic banding, persistence, and at-most-once finding creation.\n\nTreat `record_only`, `review`, and `priority` as ordinal research bands, never numeric scores. Committee relevance requires an effective-dated assignment and an exact reviewed industry rule; broad or stale evidence stays unavailable. Report source or capability failures plainly and do not substitute another source.\n"
      }
    ],
    "sources": [
      {
        "accessClassification": "public",
        "allowedOrigins": [
          "https://disclosures-clerk.house.gov"
        ],
        "canonicalUrl": "https://disclosures-clerk.house.gov/public_disc/financial-pdfs/2026FD.zip",
        "contractDigest": "ef0772fd62d5781c9dac989eb12f699856d909d10ad3b81efe6b5a68c29046bc",
        "contractVersion": "1.0.0",
        "sourceId": "house-financial-disclosures-2026"
      }
    ],
    "version": "1.1.0",
    "workspaceInstructionPath": "workspace.md",
    "contentDigest": "54b09e91047f9e34681994eefc5f1284c45b658f55873df49ba3fab3ad211630",
    "evaluations": {
      "cases": [
        {
          "fixtureId": "fixture.congressional-signals.baseline",
          "id": "congressional-signals-baseline",
          "kind": "no_match"
        },
        {
          "fixtureId": "fixture.congressional-signals.forbidden-capability",
          "id": "congressional-signals-forbidden-capability",
          "kind": "forbidden_capability"
        },
        {
          "fixtureId": "fixture.congressional-signals.non-qualifying",
          "id": "congressional-signals-non-qualifying",
          "kind": "malformed_input"
        },
        {
          "fixtureId": "fixture.congressional-signals.priority",
          "id": "congressional-signals-priority",
          "kind": "positive"
        },
        {
          "fixtureId": "fixture.congressional-signals.replay",
          "id": "congressional-signals-replay",
          "kind": "replay"
        }
      ],
      "schemaVersion": 1,
      "suiteId": "eval.congressional-signals/v1"
    },
    "workspaceInstruction": "# Congressional Signals\n\nThis workspace monitors official House Periodic Transaction Reports (PTRs) only. It is a research-triage workspace, not a trading system and not complete congressional coverage.\n\nUse only the authorized House projection and the `evaluate_congressional_signals` capability. Preserve disclosed ranges and ambiguity. Never infer intent, wrongdoing, exact value, holdings, future returns, or an instruction to trade.\n"
  },
  {
    "capabilities": {
      "hardDenied": [
        "broker.mutation",
        "coinbase_create_order",
        "filesystem",
        "interactive.approval",
        "masterkey_mcp",
        "private.history",
        "shell",
        "web.search"
      ],
      "required": [
        "evaluate_sec_ipo_source",
        "skill.public-event-monitoring"
      ]
    },
    "compatibility": {
      "coreSchemaVersion": 1,
      "strategyPackSchemaVersion": 1,
      "workspaceSchemaVersion": 1
    },
    "configuration": [
      {
        "description": "Timezone used for the local daily filing checks.",
        "key": "timezone",
        "label": "Timezone",
        "mutableAfterInstall": true,
        "pauseManagedMonitorsOnChange": true,
        "required": true,
        "rolloverGenerationOnChange": true,
        "default": "UTC",
        "kind": "iana_timezone"
      },
      {
        "description": "Unique local times when the SEC filing monitor may run.",
        "key": "dailyTimes",
        "label": "Daily check times",
        "mutableAfterInstall": true,
        "pauseManagedMonitorsOnChange": true,
        "required": true,
        "rolloverGenerationOnChange": true,
        "default": [
          "09:00",
          "16:00"
        ],
        "kind": "daily_local_times",
        "maximumItems": 8,
        "minimumItems": 1
      }
    ],
    "description": "Detect newly published SEC S-1 registrations and distinguish amendments from new candidates.",
    "displayName": "IPO Filings",
    "evaluationsPath": "evals.json",
    "id": "ipo-filings",
    "maturity": "reference",
    "monitors": [
      {
        "activationDefault": "paused",
        "alertPresentationId": "alert.public-event/v1",
        "dailyTimesConfigurationKey": "dailyTimes",
        "displayName": "Detect new S-1 filings",
        "findingSchemaId": "ipo-registration-filing/v1",
        "instructionPath": "monitors/detect-new-s1.md",
        "overridableFields": [
          "schedule"
        ],
        "requiredCapabilityIds": [
          "evaluate_sec_ipo_source"
        ],
        "resourceId": "detect-new-s1",
        "sourceIds": [
          "sec-latest-s1-filings"
        ],
        "suggestedBudget": {
          "maximumInputTokensPerRun": 10000,
          "maximumOutputTokensPerRun": 2000,
          "maximumRunsPerDay": 8
        },
        "timezoneConfigurationKey": "timezone",
        "instruction": "Evaluate only the exact declared SEC latest S-1 source for this occurrence.\nCall `evaluate_sec_ipo_source` exactly once. Preserve its canonical normalized\nfacts and classification. Complete with no match when the full window has no\nnew filing. Fail closed on an incomplete, stale, redirected, malformed, or\nunavailable source; do not use another source or capability.\n"
      }
    ],
    "schemaVersion": 1,
    "skills": [
      {
        "description": "Evaluate the exact official SEC S-1 feed for new registrations and amendments.",
        "id": "public-event-monitoring",
        "instructionPath": "playbook.md",
        "version": "1.0.0",
        "instruction": "# IPO Filings playbook\n\nUse this playbook when the owner asks about the IPO Filings strategy pack or\nthe findings produced by its managed monitor.\n\n1. Inspect the current session's exact binding and health before interpreting\n   pack state.\n2. For scheduled work, evaluate the declared SEC source exactly once through\n   `evaluate_sec_ipo_source` and keep its application-owned normalization.\n3. Classify Form S-1 as a new registration candidate and Form S-1/A as an\n   amendment. Never describe either as a completed or guaranteed IPO.\n4. Preserve accession number, CIK, form type, file number when present,\n   filed/published/observed times, canonical filing URL, content hash, and\n   source provenance.\n5. Remain silent when the complete evaluation window contains no new match.\n   Do not compensate for an incomplete or stale source by widening tools.\n"
      }
    ],
    "sources": [
      {
        "accessClassification": "public",
        "allowedOrigins": [
          "https://www.sec.gov"
        ],
        "canonicalUrl": "https://www.sec.gov/cgi-bin/browse-edgar?action=getcurrent&type=S-1&owner=include&count=40&output=atom",
        "contractDigest": "c9d9fd8e6c0881fd59692e1986b151c17df30a9e899074222098888d56127f98",
        "contractVersion": "1.0.0",
        "sourceId": "sec-latest-s1-filings"
      }
    ],
    "version": "1.0.0",
    "workspaceInstructionPath": "workspace.md",
    "contentDigest": "509e1a06a7bf2d8de6cd216ff894f9353870cc8062fff0945cde4ba7ad2a0fce",
    "evaluations": {
      "cases": [
        {
          "fixtureId": "fixture.sec-ipo.forbidden-capability",
          "id": "sec-ipo-forbidden-capability",
          "kind": "forbidden_capability"
        },
        {
          "fixtureId": "fixture.sec-ipo.malformed",
          "id": "sec-ipo-malformed-input",
          "kind": "malformed_input"
        },
        {
          "fixtureId": "fixture.sec-ipo.no-match",
          "id": "sec-ipo-no-match",
          "kind": "no_match"
        },
        {
          "fixtureId": "fixture.sec-ipo.positive",
          "id": "sec-ipo-positive",
          "kind": "positive"
        },
        {
          "fixtureId": "fixture.sec-ipo.replay",
          "id": "sec-ipo-replay",
          "kind": "replay"
        }
      ],
      "schemaVersion": 1,
      "suiteId": "eval.sec-ipo/v1"
    },
    "workspaceInstruction": "# IPO Filings\n\nThis session tracks newly published SEC S-1 registrations and distinguishes\namendments from new registration candidates. Treat every filing as public\nresearch evidence, not as proof that an IPO will occur or as investment advice.\n\nUse only the exact official SEC source and the pack-managed monitor configured\nfor this session. Preserve filing identity, classification, timestamps, and\ncanonical source provenance. Do not broaden the source set or use paid,\nprivate, financial, shell, or filesystem capabilities.\n"
  }
];
