// Generated by scripts/generate-strategy-pack-catalog.mjs. Do not edit.
// Strategy pack digests: {"ipo-filings@1.0.0":"509e1a06a7bf2d8de6cd216ff894f9353870cc8062fff0945cde4ba7ad2a0fce"}
import type { StrategyPackDefinition } from "./strategy-pack-schema";

export const STRATEGY_PACK_CATALOG_GENERATED: readonly StrategyPackDefinition[] = [
  {
    "capabilities": {
      "hardDenied": [
        "broker.mutation",
        "coinbase_create_order",
        "filesystem",
        "interactive.approval",
        "masterkey_mcp",
        "private.history",
        "shell",
        "web.search"
      ],
      "required": [
        "evaluate_sec_ipo_source",
        "skill.public-event-monitoring"
      ]
    },
    "compatibility": {
      "coreSchemaVersion": 1,
      "strategyPackSchemaVersion": 1,
      "workspaceSchemaVersion": 1
    },
    "configuration": [
      {
        "description": "Timezone used for the local daily filing checks.",
        "key": "timezone",
        "label": "Timezone",
        "mutableAfterInstall": true,
        "pauseManagedMonitorsOnChange": true,
        "required": true,
        "rolloverGenerationOnChange": true,
        "default": "UTC",
        "kind": "iana_timezone"
      },
      {
        "description": "Unique local times when the SEC filing monitor may run.",
        "key": "dailyTimes",
        "label": "Daily check times",
        "mutableAfterInstall": true,
        "pauseManagedMonitorsOnChange": true,
        "required": true,
        "rolloverGenerationOnChange": true,
        "default": [
          "09:00",
          "16:00"
        ],
        "kind": "daily_local_times",
        "maximumItems": 8,
        "minimumItems": 1
      }
    ],
    "description": "Detect newly published SEC S-1 registrations and distinguish amendments from new candidates.",
    "displayName": "IPO Filings",
    "evaluationsPath": "evals.json",
    "id": "ipo-filings",
    "maturity": "reference",
    "monitors": [
      {
        "activationDefault": "paused",
        "alertPresentationId": "alert.public-event/v1",
        "dailyTimesConfigurationKey": "dailyTimes",
        "displayName": "Detect new S-1 filings",
        "findingSchemaId": "ipo-registration-filing/v1",
        "instructionPath": "monitors/detect-new-s1.md",
        "overridableFields": [
          "schedule"
        ],
        "requiredCapabilityIds": [
          "evaluate_sec_ipo_source"
        ],
        "resourceId": "detect-new-s1",
        "sourceIds": [
          "sec-latest-s1-filings"
        ],
        "suggestedBudget": {
          "maximumInputTokensPerRun": 10000,
          "maximumOutputTokensPerRun": 2000,
          "maximumRunsPerDay": 8
        },
        "timezoneConfigurationKey": "timezone",
        "instruction": "Evaluate only the exact declared SEC latest S-1 source for this occurrence.\nCall `evaluate_sec_ipo_source` exactly once. Preserve its canonical normalized\nfacts and classification. Complete with no match when the full window has no\nnew filing. Fail closed on an incomplete, stale, redirected, malformed, or\nunavailable source; do not use another source or capability.\n"
      }
    ],
    "schemaVersion": 1,
    "skills": [
      {
        "description": "Evaluate the exact official SEC S-1 feed for new registrations and amendments.",
        "id": "public-event-monitoring",
        "instructionPath": "playbook.md",
        "version": "1.0.0",
        "instruction": "# IPO Filings playbook\n\nUse this playbook when the owner asks about the IPO Filings strategy pack or\nthe findings produced by its managed monitor.\n\n1. Inspect the current session's exact binding and health before interpreting\n   pack state.\n2. For scheduled work, evaluate the declared SEC source exactly once through\n   `evaluate_sec_ipo_source` and keep its application-owned normalization.\n3. Classify Form S-1 as a new registration candidate and Form S-1/A as an\n   amendment. Never describe either as a completed or guaranteed IPO.\n4. Preserve accession number, CIK, form type, file number when present,\n   filed/published/observed times, canonical filing URL, content hash, and\n   source provenance.\n5. Remain silent when the complete evaluation window contains no new match.\n   Do not compensate for an incomplete or stale source by widening tools.\n"
      }
    ],
    "sources": [
      {
        "accessClassification": "public",
        "allowedOrigins": [
          "https://www.sec.gov"
        ],
        "canonicalUrl": "https://www.sec.gov/cgi-bin/browse-edgar?action=getcurrent&type=S-1&owner=include&count=40&output=atom",
        "contractDigest": "c9d9fd8e6c0881fd59692e1986b151c17df30a9e899074222098888d56127f98",
        "contractVersion": "1.0.0",
        "sourceId": "sec-latest-s1-filings"
      }
    ],
    "version": "1.0.0",
    "workspaceInstructionPath": "workspace.md",
    "contentDigest": "509e1a06a7bf2d8de6cd216ff894f9353870cc8062fff0945cde4ba7ad2a0fce",
    "evaluations": {
      "cases": [
        {
          "fixtureId": "fixture.sec-ipo.forbidden-capability",
          "id": "sec-ipo-forbidden-capability",
          "kind": "forbidden_capability"
        },
        {
          "fixtureId": "fixture.sec-ipo.malformed",
          "id": "sec-ipo-malformed-input",
          "kind": "malformed_input"
        },
        {
          "fixtureId": "fixture.sec-ipo.no-match",
          "id": "sec-ipo-no-match",
          "kind": "no_match"
        },
        {
          "fixtureId": "fixture.sec-ipo.positive",
          "id": "sec-ipo-positive",
          "kind": "positive"
        },
        {
          "fixtureId": "fixture.sec-ipo.replay",
          "id": "sec-ipo-replay",
          "kind": "replay"
        }
      ],
      "schemaVersion": 1,
      "suiteId": "eval.sec-ipo/v1"
    },
    "workspaceInstruction": "# IPO Filings\n\nThis session tracks newly published SEC S-1 registrations and distinguishes\namendments from new registration candidates. Treat every filing as public\nresearch evidence, not as proof that an IPO will occur or as investment advice.\n\nUse only the exact official SEC source and the pack-managed monitor configured\nfor this session. Preserve filing identity, classification, timestamps, and\ncanonical source provenance. Do not broaden the source set or use paid,\nprivate, financial, shell, or filesystem capabilities.\n"
  }
];
